language: scala
script:
- sbt -jvm-opts travis/jvmopts.build ++$TRAVIS_SCALA_VERSION clean test
scala: 
- 2.10.4
notifications: 
  email: fborrego@gilt.com
jdk: 
- oraclejdk7
env: 
  global: 
  - secure: UeqQnJFrKWGVmmCMypWAThkjdXZCN17jHMfi6JZe1cb59hEZSo/LxcP0ZF+IYjUc3Qaj7o1sdlT4yqpoYNvAG7FLsjOOUPmHYenVpR6lJgHlmkU5cTQYPc1Em9k6XEpiuuNEdRg757TDMlzbz4MA5fZCE5rKpN6ZR5GTYHt97ws=
  - secure: gfUWdGw0N7SHU6wRVnJmuYASx69Wz6aMOFHiTzmlPuVjqKu2om1ucv6L+YRUUuihm3VhN4JJkemGNi7x8VQrffIIq9aRGOn+esw7XwggIX09mwsQPOwrrZVifvgELb8CHUy+NnPAM8LTg3RIDfhUMwT6jOTyEgJlcjyVva2V9s0=
after_success:
  - >
      test "${TRAVIS_PULL_REQUEST}" = 'false' &&
      test "${TRAVIS_JDK_VERSION}" = 'oraclejdk7' &&
      sh "$TRAVIS_BUILD_DIR/.travis-ci-bintray-credentials.sh" &&
      sbt 'set version := version.value + "." + System.getenv("TRAVIS_BUILD_NUMBER")' publish